name: Eml-Parser_codeQC

on:
  push:
    branches:
      - master
    paths:
      - '*'

# A - workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
   sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: SonarQube Scan
      run: |
         cd /root/actions-runner/_work/Eml-Parser/Eml-Parser/
         sonar-scanner -D sonar.login="${{ secrets.SONARQUBE_USER }}" -D sonar.password="${{ secrets.SONARQUBE_PASSWORD }}"
